basePath: /
host: localhost:8080
info:
  contact: {}
  description: API Server for test work
  title: International Trade API
  version: 1.0.0
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
