services:

  postgres:
    container_name: inter_trade_pgdb
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5436:5432"
    restart: unless-stopped

  app:
    container_name: inter_trade
    build: .
    # volumes:
    #   - ./logs:/logs
    #   - ./secrets:/secrets
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg-data:
